[project]
name = "lottery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "binance-futures-connector>=4.1.0",
    "configparser>=7.2.0",
    "flask>=3.1.0",
    "tzdata>=2025.2",
]
